language: node_js
node_js:
  - lts/*
before_deploy:
  - cd docs
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
after_deploy:
  - cd ..